Refactor top-level LSST metadetect
esheldon/metadetect pull request #223
Opened 2024-10-21 19:46 UTC by arunkannawadi

This is a preview of the refactoring I mentioned in #220 . It currently refactors only the top-most level making run_metadetect, which is the typical entry point, a wrapper around a Task. The extensive coverage with unit tests should make us all feel confident going about such refactoring. The fact that the the unit tests pass without any changes also shows that the public APIs remain unchanged.

2024-10-31 16:10 UTC, ismael-mendoza commented on metadetect/lsst/measure.py
> +        doc="Measuremetn config",
```suggestion
        doc="Measurement config",
```

2024-10-31 20:43 UTC, beckermr requested changes
Why were the ngmix upstream tests removed?

Ditto for the extra test skeips etc. All of that needs to be backed out before we can consider merging this.

2024-11-01 00:23 UTC, arunkannawadi commented
Thanks to @ismael-mendoza for doing the big chunk of this work. We've tested this by also running the shear recovery tests in `descwl-shear-sims` (shear_test_descwl/test_shear_meas) and that seems to pass.

2025-01-31 22:34 UTC, arunkannawadi commented
@esheldon @beckermr - have you had a chance to go through this PR?

2025-02-10 19:47 UTC, esheldon commented
This looks OK to me.  I think we need to run it at scale to stress test it, and look at outputs for sanity checks.

2025-02-10 20:59 UTC, arunkannawadi commented
I am happy to run extensive tests but would need some handholding to get started.

2025-02-11 12:37 UTC, beckermr requested changes
I have some comments/questions. Sorry for the delay!

2025-02-11 12:37 UTC, beckermr commented on metadetect/lsst/measure.py
> +        self.detect.reEstimateBackground = True
This one is listed twice, see below.

2025-02-11 12:37 UTC, beckermr commented on metadetect/lsst/measure.py
> +        self.detect.reEstimateBackground = False
This is the other entry.

2025-02-11 12:37 UTC, beckermr commented on metadetect/lsst/metadetect.py
> +    )
I think the units here are arcseconds?

2025-02-11 12:37 UTC, beckermr commented on metadetect/lsst/skysub.py
> +SourceDetectionTask.ConfigClass = SourceDetectionConfig
This bit of config boilerplate is repeated from the measure module. If one instance of this code needs to be changed, does the other one need to be changed too? If yes, then we should have this bit of boilerplate appear only once.

2025-02-11 12:37 UTC, beckermr commented on metadetect/lsst/skysub.py
> +        return self._sky_sub(exposure, **kwargs)
Where is this method defined? It doesn't look like this should be attached to the Task class. Does it happen on-the-fly after that calls to makeSubtask?

2025-02-11 12:37 UTC, beckermr commented on metadetect/lsst/util.py
> +    stats_mask = ['BAD', 'EDGE', 'DETECTED', 'DETECTED_NEGATIVE', 'NO_DATA', 'BRIGHT']
There are changes in the logic here around BRIGHT handling. Are those inteneded?

2025-03-03 17:42 UTC, arunkannawadi commented on metadetect/lsst/skysub.py
> +        return self._sky_sub(exposure, **kwargs)
Agree! This looks like a bug. I'll look into it.

2025-03-03 17:42 UTC, arunkannawadi commented on metadetect/lsst/util.py
> +    stats_mask = ['BAD', 'EDGE', 'DETECTED', 'DETECTED_NEGATIVE', 'NO_DATA', 'BRIGHT']
Yes, these are intentional changes but there is no logic change here. The change was required was to keep this function not depend on any specific `Exposure` object `exp` . Instead of looking if `exp` has a `BRIGHT` mask plane and adding to this list, we always add it to the list. If `exp` does not have it defined, then the `addMaskPlane` call above defines it but doesn't set the bit in any pixel and everything proceeds as before. If it has `BRIGHT` plane defined already, then `addMaskPlane` call doesn't do anything and everything proceeds as before as well.

2025-03-06 23:01 UTC, arunkannawadi commented on metadetect/lsst/skysub.py
> +        return self._sky_sub(exposure, **kwargs)
This turned out to be some extra bit of lines that weren't being used anywhere. Removed them.

2025-03-06 23:04 UTC, arunkannawadi reviewed
I made changes/addressed the questions from previous review and I think this is ready for another round of review, Matt.

2025-03-10 17:30 UTC, beckermr requested changes
LGTM on the code! One more request.

Can we add some documentation somewhere or links to it to explain a bit about how the config works, how we can ensure the config is not changed, etc.? 

We had a ton of discussion on this, but I forgot the results and it feels like we should write it down.

2025-03-20 15:58 UTC, arunkannawadi commented
I've added a README to the `lsst` subpackage explaining some of this. Let me know what else you'd like to see.

Additionally, I'd like to include `py3.12` to the matrix test (not necessarily in this PR though) but it looks like it couldn't find consistent set of dependencies. GitHub Actions log [here](https://github.com/esheldon/metadetect/actions/runs/13710064653/job/38344479994).

2025-03-20 16:04 UTC, beckermr commented
Looks like sep is not on numpy2 yet and the feedstock is falling behind. I am working on it now.

2025-03-20 16:08 UTC, arunkannawadi commented
Thank you! However, the LSST-specific tests, which is where I tried adding 3.12 should not require `sep` at all in the first place. It looks like it's trying to install everything in `requirements.txt` when only a subset of them are required for the `lsst` subpackage. `sxdes` is another one that's not required.

2025-03-20 16:10 UTC, beckermr commented
Ah we can fix that as well by separating out the files. Are you adding 3.12 here or in another PR?

2025-03-20 16:13 UTC, arunkannawadi commented
I will add 3.12 in another PR.

2025-03-20 16:22 UTC, beckermr commented
@arunkannawadi I can help there to separate out the requirements if needed!

2025-03-20 16:23 UTC, beckermr approved these changes

2025-03-20 16:25 UTC, beckermr commented
@esheldon you ok to merge here?

2025-03-20 19:07 UTC, merged